// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SkipTitleScreen","status":true,"description":"Skip the title screen and starts a new game immediately.","parameters":{"Fade In Mode":"1","Fade In Speed":"120"}},
{"name":"MessageSpeedMod","status":true,"description":"Adjust text showing speed in message window.","parameters":{}}
];
